### ISSUE TITLE
How to dispose a listener

### ISSUE THREAD

**Issue by sanihaq** [lukehutch/flutter_reactive_value#3]
What's the best way to dispose a listener?
```dart
...
 @override
  void dispose() {
   // on dispose
    super.dispose();
  }

...
//  reactive value is in nested child
child: Builder(builder: (context) {
  final val = value.reactiveValue(context);
  return Text(val);
})
```

**Comment by lukehutch** [comment]
There's no need to dispose the listener. A listener is added to the `ValueNotifier` when you call `value.reactiveValue(context)`, and when the value changes, if the `context` (the underlying `Element`) still exists (is mounted), then the `context` is rebuilt. Then, whether the `context` exists or not, the listener is automatically removed from the `ValueNotifier`. Another listener will be added by the new call to `build`.

https://github.com/lukehutch/flutter_reactive_value/blob/main/lib/src/reactive_value_notifier.dart
