### ISSUE TITLE
Awesome! This is the best state management tool for flutter beginners!

### ISSUE THREAD

**Issue by nt1r** [lukehutch/flutter_reactive_value#4]
Hi! I'm a Flutter beginner coming from Android development. I have tried serveral state management approaches in Flutter offical document. [I come from here.](https://docs.flutter.dev/data-and-backend/state-mgmt/options) Most of them are not very easy to use(high learning cost), and not friendly to beginners. Thanks god, the last one in the document saves my day! Yes, this tool is soooo awesome!

Advantages: 
- very easy to use, friendly to beginners
- similar state management experience for those who come from Android Compose
- easy to integrate into a viewmodel

Starred! Keep forward :D

**Comment by lukehutch** [comment]
Thanks! I did my best to make it as simple to use as possible.

Somebody pointed out to me after I released this though that I'm basically doing the same thing as `ValueListenableBuilder`, albeit with a bit less boilerplate syntax. They're actually right about that. So sometimes I just use `ValueListenableBuilder` now.
